// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations.SlopeSourceDb
{
    [DbContext(typeof(SlopeSourceDbContext))]
    [Migration("20210216051955_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.ApplicationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("log_time");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.HasKey("Id");

                    b.ToTable("ss_tb_application_log");
                });

            modelBuilder.Entity("Domain.Entities.GlobalConfigChangeLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConfigCategory")
                        .HasColumnType("int")
                        .HasColumnName("config_category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("GcaOid")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gca_oid");

                    b.Property<string>("GlobalConfigJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("global_config_json");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("log_time");

                    b.Property<long?>("OMSerialId")
                        .HasColumnType("bigint")
                        .HasColumnName("om_serial_id");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("reference_id");

                    b.Property<string>("SecurityServerId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("security_server_id");

                    b.Property<int>("StateChange")
                        .HasColumnType("int")
                        .HasColumnName("state_change");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceId", "ConfigCategory", "StateChange");

                    b.ToTable("tr_tb_global_config_change_log");
                });
#pragma warning restore 612, 618
        }
    }
}
